# Supplement numerical tables — source data

Companion notebook to `SUPPLEMENT_TABLES_DRAFT.md`. Every table in that file
is computed by `scripts/6n_supplement_table_export.py`; this notebook calls
the same functions directly and displays the underlying per-row data as
DataFrames, so the numbers in the draft markdown can be checked against their
source caches without re-deriving anything by hand.

`supplement_revision.tex` is never touched by this notebook or by
`6n_supplement_table_export.py` — see the note at the top of
`SUPPLEMENT_TABLES_DRAFT.md` for why.

In [1]:
import os, sys
sys.path.insert(0, os.path.abspath('..'))
os.chdir('..')

import importlib.util
import pandas as pd

spec = importlib.util.spec_from_file_location("supp_tables", "scripts/6n_supplement_table_export.py")
t = importlib.util.module_from_spec(spec)
spec.loader.exec_module(t)

## Figure 3 — single-forcing baseline vs. Opt. Priority 1 (eval: Priority 1)

5 agents x {Baseline, Opt. Priority 1}, 50-seed [p25, p50, p75].

In [2]:
rows = t.compute_fig3_table()
df_fig3 = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in rows]).drop(columns="pctl")
df_fig3

    agent           config        eval     p25     p50     p75
0     CO2         Baseline  Priority 1  0.0495  0.0549  0.0596
1     CO2  Opt. Priority 1  Priority 1  0.0243  0.0284  0.0322
2     CH4         Baseline  Priority 1  0.0171  0.0180  0.0187
3     CH4  Opt. Priority 1  Priority 1  0.0127  0.0141  0.0154
4     N2O         Baseline  Priority 1  0.0170  0.0197  0.0247
5     N2O  Opt. Priority 1  Priority 1  0.0134  0.0178  0.0291
6  Sulfur         Baseline  Priority 1  0.0165  0.0169  0.0172
7  Sulfur  Opt. Priority 1  Priority 1  0.0117  0.0131  0.0142
8      BC         Baseline  Priority 1  0.0123  0.0138  0.0160
9      BC  Opt. Priority 1  Priority 1  0.0101  0.0118  0.0139

## Figure 5 — multi-agent baseline vs. Opt. Priority 1 (eval: Priority 1)

In [3]:
rows = t.compute_fig5_table()
df_fig5 = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in rows]).drop(columns="pctl")
df_fig5

   agent           config        eval     p25     p50     p75
0  Multi         Baseline  Priority 1  0.0577  0.0676  0.0845
1  Multi  Opt. Priority 1  Priority 1  0.0377  0.0571  0.0718

## Figure 4 — CO2-only and Multi, full 6-config x 5-eval-set grid

Source: `fig4_seed_spread_co2_only.pkl` + `fig4_seed_spread_all_agents_smooth.pkl`.

In [4]:
fig4 = t.compute_fig4_table()
df_fig4_co2 = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in fig4["co2"]]).drop(columns="pctl")
df_fig4_multi = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in fig4["multi"]]).drop(columns="pctl")
df_fig4_co2

   agent           config        eval     p25     p50     p75
0    CO2         Baseline  Priority 1  0.0495  0.0549  0.0596
1    CO2         Baseline  Priority 2  0.1115  0.1147  0.1184
2    CO2         Baseline        DECK  0.0417  0.0499  0.0599
3    CO2         Baseline         CS3  0.0468  0.0517  0.0595
4    CO2         Baseline         All  0.1041  0.1070  0.1090
5    CO2  Opt. Priority 1  Priority 1  0.0243  0.0284  0.0322
6    CO2  Opt. Priority 1  Priority 2  0.0706  0.0761  0.0807
7    CO2  Opt. Priority 1        DECK  0.0468  0.0628  0.0746
8    CO2  Opt. Priority 1         CS3  0.0082  0.0121  0.0142
9    CO2  Opt. Priority 1         All  0.0584  0.0628  0.0686
10   CO2  Opt. Priority 2  Priority 1  0.0296  0.0338  0.0413
11   CO2  Opt. Priority 2  Priority 2  0.0553  0.0603  0.0695
12   CO2  Opt. Priority 2        DECK  0.0418  0.0538  0.0670
13   CO2  Opt. Priority 2         CS3  0.0150  0.0208  0.0271
14   CO2  Opt. Priority 2         All  0.0514  0.0574  0.0642
15   CO2        Opt. DECK  Priority 1  0.0810  0.0989  0.1241
16   CO2        Opt. DECK  Priority 2  0.1180  0.1286  0.1454
17   CO2        Opt. DECK        DECK  0.0151  0.0184  0.0231
18   CO2        Opt. DECK         CS3  0.0387  0.0457  0.0562
19   CO2        Opt. DECK         All  0.1048  0.1158  0.1352
20   CO2         Opt. CS3  Priority 1  0.0481  0.0588  0.0723
21   CO2         Opt. CS3  Priority 2  0.0933  0.1000  0.1125
22   CO2         Opt. CS3        DECK  0.0657  0.0736  0.0907
23   CO2         Opt. CS3         CS3  0.0030  0.0040  0.0055
24   CO2         Opt. CS3         All  0.0780  0.0887  0.1007
25   CO2         Opt. All  Priority 1  0.0274  0.0305  0.0358
26   CO2         Opt. All  Priority 2  0.0612  0.0667  0.0721
27   CO2         Opt. All        DECK  0.0357  0.0427  0.0603
28   CO2         Opt. All         CS3  0.0109  0.0123  0.0151
29   CO2         Opt. All         All  0.0507  0.0543  0.0593

In [5]:
df_fig4_multi

    agent           config        eval     p25     p50     p75
0   Multi         Baseline  Priority 1  0.0577  0.0676  0.0845
1   Multi         Baseline  Priority 2  0.1803  0.1970  0.2172
2   Multi         Baseline        DECK  0.5463  0.5915  0.6403
3   Multi         Baseline         CS3  0.3751  0.5172  0.6120
4   Multi         Baseline         All  0.2190  0.2519  0.2661
5   Multi  Opt. Priority 1  Priority 1  0.0376  0.0565  0.0717
6   Multi  Opt. Priority 1  Priority 2  0.1890  0.2096  0.2414
7   Multi  Opt. Priority 1        DECK  0.4120  0.4608  0.5059
8   Multi  Opt. Priority 1         CS3  0.1369  0.2005  0.2930
9   Multi  Opt. Priority 1         All  0.1806  0.1973  0.2133
10  Multi  Opt. Priority 2  Priority 1  0.1898  0.2732  0.3678
11  Multi  Opt. Priority 2  Priority 2  0.0795  0.0936  0.1198
12  Multi  Opt. Priority 2        DECK  0.2822  0.3312  0.4015
13  Multi  Opt. Priority 2         CS3  0.1634  0.2058  0.2529
14  Multi  Opt. Priority 2         All  0.1684  0.2181  0.2604
15  Multi        Opt. DECK  Priority 1  1.9643  2.5712  3.2585
16  Multi        Opt. DECK  Priority 2  1.3295  1.6260  2.0906
17  Multi        Opt. DECK        DECK  0.0618  0.0779  0.1010
18  Multi        Opt. DECK         CS3  1.3068  1.5369  2.2264
19  Multi        Opt. DECK         All  1.7029  2.2127  2.8739
20  Multi         Opt. CS3  Priority 1  0.2896  0.3627  0.4658
21  Multi         Opt. CS3  Priority 2  0.3007  0.3417  0.3814
22  Multi         Opt. CS3        DECK  0.6083  0.7073  0.7886
23  Multi         Opt. CS3         CS3  0.0058  0.0069  0.0087
24  Multi         Opt. CS3         All  0.3631  0.4092  0.4527
25  Multi         Opt. All  Priority 1  0.0711  0.0874  0.1062
26  Multi         Opt. All  Priority 2  0.0897  0.1034  0.1256
27  Multi         Opt. All        DECK  0.2020  0.2274  0.2647
28  Multi         Opt. All         CS3  0.0534  0.0859  0.1237
29  Multi         Opt. All         All  0.0959  0.1145  0.1415

## Figure 6 — R2 forest-plot data (OOD scenarios)

Source: `data/SI_results/fig6_ood/fig6_ood_r2_table_fig6.csv` (already median+p25+p75 across 50 seeds).

In [6]:
rows = t.compute_fig6_table()
df_fig6 = pd.DataFrame(rows)
df_fig6[["p25", "p50", "p75"]] = pd.DataFrame(df_fig6["pctl"].tolist(), index=df_fig6.index)
df_fig6 = df_fig6.drop(columns="pctl")
df_fig6

      scenario        config metric  n_seeds    p25    p50    p75
0   H-ext-Maer  Baseline Em.     R2       50  0.225  0.425  0.617
1   H-ext-Maer      Opt. All     R2       50  0.958  0.981  0.991
2   H-ext-Maer    Opt. DAMIP     R2       50  0.557  0.692  0.810
3   H-ext-Maer   Opt. GeoMIP     R2       50  0.811  0.912  0.977
4   H-ext-Maer   Opt. Tier 1     R2       50  0.957  0.983  0.992
..         ...           ...    ...      ...    ...    ...    ...
60    G6sulfur  Baseline Em.     R2       50 -1.356 -0.728 -0.025
61    G6sulfur      Opt. All     R2       50  0.994  0.996  0.999
62    G6sulfur    Opt. DAMIP     R2       50 -0.314  0.328  0.651
63    G6sulfur   Opt. GeoMIP     R2       50  0.999  1.000  1.000
64    G6sulfur   Opt. Tier 1     R2       50 -0.615 -0.058  0.715

[65 rows x 7 columns]

## Figure 7 — MESM, top50_overall seed selection

**Disclosure**: computed over the 50 of N seeds with the lowest combined Tier1:7/Tier2:5/DECK:2/CS3:2-weighted NRMSE across the three optimized MESM variants — not the full unselected seed sample. See `6m_fig7_seed_selection_variants.ipynb` for the selection method.

In [7]:
fig7 = t.compute_fig7_table()
print(fig7["note"])
print(f"n_total_seeds={fig7['n_total_seeds']}, n_selected={fig7['n_selected']}, selection={fig7['selection']}")
df_fig7 = pd.DataFrame(fig7["rows"])
df_fig7[["p25", "p50", "p75"]] = pd.DataFrame(df_fig7["pctl"].tolist(), index=df_fig7.index)
df_fig7 = df_fig7.drop(columns="pctl")
df_fig7

Computed over the 50 of 1000 seeds with the lowest combined weighted NRMSE across all three optimized MESM variants (Tier1:7/Tier2:5/DECK:2/CS3:2 weights), not the full unselected seed sample.
n_total_seeds=1000, n_selected=50, selection=top50_overall

           config    eval     p25     p50     p75
0        Baseline  Tier 1  0.0424  0.0432  0.0449
1        Baseline  Tier 2  0.0913  0.0939  0.0954
2        Baseline    DECK  0.1692  0.1707  0.1727
3        Baseline     CS3  0.0602  0.0616  0.0632
4   Opt. Constant  Tier 1  0.0836  0.0875  0.0891
5   Opt. Constant  Tier 2  0.0816  0.0875  0.0915
6   Opt. Constant    DECK  0.2016  0.2067  0.2131
7   Opt. Constant     CS3  0.0705  0.0731  0.0756
8       Opt. Sine  Tier 1  0.0714  0.0784  0.0822
9       Opt. Sine  Tier 2  0.0813  0.0868  0.0926
10      Opt. Sine    DECK  0.1546  0.1593  0.1662
11      Opt. Sine     CS3  0.0694  0.0749  0.0826
12      Opt. Both  Tier 1  0.0742  0.0776  0.0801
13      Opt. Both  Tier 2  0.0659  0.0722  0.0752
14      Opt. Both    DECK  0.1787  0.1827  0.1848
15      Opt. Both     CS3  0.0777  0.0805  0.0839

## SI extended-results — CH4 / N2O / Sulfur / BC

Same 6-config x 5-eval-set grid as Figure 4, one table per agent. CO2's own
panel is not duplicated here — it is identical to Figure 4's CO2-only half
above (same source cache).

**Known-corrected bug**: `regenerate_SI_extended_results_cache_seed_sweep`
was not forwarding `batch_size` to its `evaluate_optimal_emulator` call,
so N2O (batch_size=16), Sulfur (64), and BC (32) were silently re-evaluated
full-batch instead of at their actual trained minibatch size — this inverted
the reported conclusion for N2O and BC. Fixed in `utils_inverse.py`; every
`SI_extended_seed_spread_{agent}.pkl` built before the fix is stale for
N2O/Sulfur/BC. CH4 (batch_size=None) was unaffected by construction.

In [8]:
try:
    rows = t.compute_si_extended_table('CH4')
    df = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in rows]).drop(columns="pctl")
except FileNotFoundError as e:
    df = None
    print(f"PENDING - cache not yet rebuilt: {e}")
globals()[f"df_si_ch4"] = df
df

   agent           config        eval     p25     p50     p75
0    CH4         Baseline  Priority 1  0.0171  0.0180  0.0187
1    CH4         Baseline  Priority 2  0.0145  0.0152  0.0160
2    CH4         Baseline        DECK  0.0420  0.0451  0.0494
3    CH4         Baseline         CS3  0.0175  0.0188  0.0198
4    CH4         Baseline         All  0.0190  0.0197  0.0208
5    CH4  Opt. Priority 1  Priority 1  0.0127  0.0141  0.0154
6    CH4  Opt. Priority 1  Priority 2  0.0117  0.0124  0.0136
7    CH4  Opt. Priority 1        DECK  0.0383  0.0476  0.0543
8    CH4  Opt. Priority 1         CS3  0.0147  0.0164  0.0180
9    CH4  Opt. Priority 1         All  0.0173  0.0186  0.0201
10   CH4  Opt. Priority 2  Priority 1  0.0153  0.0164  0.0176
11   CH4  Opt. Priority 2  Priority 2  0.0111  0.0119  0.0128
12   CH4  Opt. Priority 2        DECK  0.0414  0.0477  0.0551
13   CH4  Opt. Priority 2         CS3  0.0168  0.0180  0.0194
14   CH4  Opt. Priority 2         All  0.0182  0.0197  0.0207
15   CH4        Opt. DECK  Priority 1  0.0227  0.0269  0.0321
16   CH4        Opt. DECK  Priority 2  0.0236  0.0309  0.0397
17   CH4        Opt. DECK        DECK  0.0120  0.0146  0.0184
18   CH4        Opt. DECK         CS3  0.0147  0.0158  0.0183
19   CH4        Opt. DECK         All  0.0232  0.0268  0.0320
20   CH4         Opt. CS3  Priority 1  0.0397  0.0489  0.0567
21   CH4         Opt. CS3  Priority 2  0.0286  0.0355  0.0449
22   CH4         Opt. CS3        DECK  0.0610  0.0723  0.0884
23   CH4         Opt. CS3         CS3  0.0049  0.0073  0.0098
24   CH4         Opt. CS3         All  0.0377  0.0483  0.0555
25   CH4         Opt. All  Priority 1  0.0147  0.0157  0.0166
26   CH4         Opt. All  Priority 2  0.0114  0.0120  0.0126
27   CH4         Opt. All        DECK  0.0283  0.0325  0.0377
28   CH4         Opt. All         CS3  0.0147  0.0160  0.0171
29   CH4         Opt. All         All  0.0158  0.0168  0.0180

In [9]:
try:
    rows = t.compute_si_extended_table('N2O')
    df = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in rows]).drop(columns="pctl")
except FileNotFoundError as e:
    df = None
    print(f"PENDING - cache not yet rebuilt: {e}")
globals()[f"df_si_n2o"] = df
df

   agent           config        eval     p25     p50     p75
0    N2O         Baseline  Priority 1  0.0170  0.0197  0.0247
1    N2O         Baseline  Priority 2  0.0179  0.0231  0.0304
2    N2O         Baseline        DECK  0.2779  0.3260  0.3790
3    N2O         Baseline         CS3  0.0098  0.0132  0.0173
4    N2O         Baseline         All  0.0449  0.0505  0.0556
5    N2O  Opt. Priority 1  Priority 1  0.0134  0.0178  0.0291
6    N2O  Opt. Priority 1  Priority 2  0.0168  0.0210  0.0348
7    N2O  Opt. Priority 1        DECK  0.1953  0.2457  0.2833
8    N2O  Opt. Priority 1         CS3  0.0103  0.0133  0.0190
9    N2O  Opt. Priority 1         All  0.0361  0.0422  0.0509
10   N2O  Opt. Priority 2  Priority 1  0.0276  0.0466  0.0626
11   N2O  Opt. Priority 2  Priority 2  0.0126  0.0170  0.0268
12   N2O  Opt. Priority 2        DECK  0.1791  0.2361  0.3062
13   N2O  Opt. Priority 2         CS3  0.0154  0.0185  0.0287
14   N2O  Opt. Priority 2         All  0.0434  0.0551  0.0630
15   N2O        Opt. DECK  Priority 1  0.0791  0.1254  0.2379
16   N2O        Opt. DECK  Priority 2  0.0638  0.1436  0.2623
17   N2O        Opt. DECK        DECK  0.0461  0.0556  0.0661
18   N2O        Opt. DECK         CS3  0.0382  0.0747  0.1461
19   N2O        Opt. DECK         All  0.0673  0.1259  0.2295
20   N2O         Opt. CS3  Priority 1  0.0350  0.0435  0.0574
21   N2O         Opt. CS3  Priority 2  0.0304  0.0378  0.0467
22   N2O         Opt. CS3        DECK  0.2116  0.2948  0.3467
23   N2O         Opt. CS3         CS3  0.0035  0.0057  0.0103
24   N2O         Opt. CS3         All  0.0562  0.0647  0.0746
25   N2O         Opt. All  Priority 1  0.0171  0.0240  0.0401
26   N2O         Opt. All  Priority 2  0.0180  0.0239  0.0322
27   N2O         Opt. All        DECK  0.1160  0.1527  0.1808
28   N2O         Opt. All         CS3  0.0132  0.0170  0.0223
29   N2O         Opt. All         All  0.0305  0.0380  0.0456

In [10]:
try:
    rows = t.compute_si_extended_table('Sulfur')
    df = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in rows]).drop(columns="pctl")
except FileNotFoundError as e:
    df = None
    print(f"PENDING - cache not yet rebuilt: {e}")
globals()[f"df_si_sulfur"] = df
df

     agent           config        eval     p25     p50     p75
0   Sulfur         Baseline  Priority 1  0.0165  0.0169  0.0172
1   Sulfur         Baseline  Priority 2  0.0187  0.0189  0.0193
2   Sulfur         Baseline        DECK  0.1199  0.1234  0.1285
3   Sulfur         Baseline         CS3  0.0107  0.0110  0.0117
4   Sulfur         Baseline         All  0.0266  0.0270  0.0276
5   Sulfur  Opt. Priority 1  Priority 1  0.0117  0.0131  0.0142
6   Sulfur  Opt. Priority 1  Priority 2  0.0151  0.0168  0.0181
7   Sulfur  Opt. Priority 1        DECK  0.0929  0.1103  0.1336
8   Sulfur  Opt. Priority 1         CS3  0.0098  0.0114  0.0137
9   Sulfur  Opt. Priority 1         All  0.0223  0.0235  0.0257
10  Sulfur  Opt. Priority 2  Priority 1  0.0164  0.0178  0.0195
11  Sulfur  Opt. Priority 2  Priority 2  0.0119  0.0142  0.0152
12  Sulfur  Opt. Priority 2        DECK  0.1055  0.1326  0.1595
13  Sulfur  Opt. Priority 2         CS3  0.0126  0.0151  0.0214
14  Sulfur  Opt. Priority 2         All  0.0239  0.0259  0.0284
15  Sulfur        Opt. DECK  Priority 1  0.0645  0.1001  0.1618
16  Sulfur        Opt. DECK  Priority 2  0.0709  0.1149  0.1743
17  Sulfur        Opt. DECK        DECK  0.0453  0.0479  0.0533
18  Sulfur        Opt. DECK         CS3  0.0312  0.0706  0.1437
19  Sulfur        Opt. DECK         All  0.0599  0.0930  0.1455
20  Sulfur         Opt. CS3  Priority 1  0.0818  0.1035  0.1204
21  Sulfur         Opt. CS3  Priority 2  0.1133  0.1473  0.1782
22  Sulfur         Opt. CS3        DECK  0.1014  0.1182  0.1375
23  Sulfur         Opt. CS3         CS3  0.0014  0.0019  0.0024
24  Sulfur         Opt. CS3         All  0.0867  0.1080  0.1309
25  Sulfur         Opt. All  Priority 1  0.0149  0.0164  0.0178
26  Sulfur         Opt. All  Priority 2  0.0152  0.0161  0.0174
27  Sulfur         Opt. All        DECK  0.0650  0.0742  0.0826
28  Sulfur         Opt. All         CS3  0.0072  0.0092  0.0120
29  Sulfur         Opt. All         All  0.0187  0.0197  0.0210

In [11]:
try:
    rows = t.compute_si_extended_table('BC')
    df = pd.DataFrame([{**r, "p25": r["pctl"][0], "p50": r["pctl"][1], "p75": r["pctl"][2]} for r in rows]).drop(columns="pctl")
except FileNotFoundError as e:
    df = None
    print(f"PENDING - cache not yet rebuilt: {e}")
globals()[f"df_si_bc"] = df
df

   agent           config        eval     p25     p50     p75
0     BC         Baseline  Priority 1  0.0123  0.0138  0.0160
1     BC         Baseline  Priority 2  0.0123  0.0134  0.0151
2     BC         Baseline        DECK  0.1848  0.2019  0.2165
3     BC         Baseline         CS3  0.0123  0.0166  0.0242
4     BC         Baseline         All  0.0295  0.0319  0.0334
5     BC  Opt. Priority 1  Priority 1  0.0101  0.0118  0.0139
6     BC  Opt. Priority 1  Priority 2  0.0104  0.0122  0.0154
7     BC  Opt. Priority 1        DECK  0.0653  0.0780  0.1043
8     BC  Opt. Priority 1         CS3  0.0123  0.0157  0.0183
9     BC  Opt. Priority 1         All  0.0176  0.0199  0.0223
10    BC  Opt. Priority 2  Priority 1  0.0119  0.0138  0.0162
11    BC  Opt. Priority 2  Priority 2  0.0099  0.0118  0.0147
12    BC  Opt. Priority 2        DECK  0.0675  0.0833  0.1189
13    BC  Opt. Priority 2         CS3  0.0153  0.0188  0.0231
14    BC  Opt. Priority 2         All  0.0182  0.0218  0.0244
15    BC        Opt. DECK  Priority 1  0.1409  0.2048  0.4267
16    BC        Opt. DECK  Priority 2  0.1434  0.1960  0.3834
17    BC        Opt. DECK        DECK  0.0648  0.0807  0.0938
18    BC        Opt. DECK         CS3  0.1522  0.2173  0.4872
19    BC        Opt. DECK         All  0.1418  0.1878  0.3934
20    BC         Opt. CS3  Priority 1  0.0138  0.0178  0.0287
21    BC         Opt. CS3  Priority 2  0.0166  0.0215  0.0312
22    BC         Opt. CS3        DECK  0.0635  0.0802  0.1103
23    BC         Opt. CS3         CS3  0.0051  0.0088  0.0139
24    BC         Opt. CS3         All  0.0208  0.0254  0.0359
25    BC         Opt. All  Priority 1  0.0109  0.0136  0.0156
26    BC         Opt. All  Priority 2  0.0104  0.0126  0.0149
27    BC         Opt. All        DECK  0.0654  0.0779  0.0893
28    BC         Opt. All         CS3  0.0118  0.0163  0.0192
29    BC         Opt. All         All  0.0172  0.0194  0.0216

## Table S2 (`tab:supp_opt_v_dyn`) — Multi row

Computed by the newly extended `scripts/6b_iteration0_ablation.py` (added a
`"Multi"` entry to `AGENT_CONFIG`/`FIG_GROUPS`): `Opt. Iter. 0` / `Opt. Final`
are read directly from the existing `checkpoints/multi_fig4_smooth/seed_sweep`
tier1-optimized checkpoints (same source as the Figure 4/5 Multi panels);
`Unopt. Rich` comes from 100 new `--mode control` runs (50 seeds x
{sine, gaussian} IC, `num_updates=0`) run on Engaging. All values are medians
across 50 seeds, evaluated on Priority 1.

**Flag**: every existing single-agent row uses Gaussian as the "best
performing" dynamically-rich IC (per the table's caption). For Multi,
**sine outperforms Gaussian** (lower median NRMSE) — the opposite of every
single-forcing agent. The row below uses sine, consistent with the caption's
"best performing" selection rule, but this means the caption's parenthetical
"(Gaussian)" is no longer accurate as a blanket statement once Multi is
added.

In [12]:
import pickle
import numpy as np
import utils_inverse

N = 50
opt_iter0, opt_final = [], []
for seed in range(N):
    p = f'checkpoints/multi_fig4_smooth/seed_sweep/inverse_constant_tier1_multi_fig4_seed{seed}.pkl'
    ckpt = utils_inverse.load_inverse_ckpt(p)
    nrmse = utils_inverse.recover_nrmse_trajectory(ckpt)
    opt_iter0.append(float(nrmse[0]))
    opt_final.append(float(nrmse[-1]))

def load_control(ic):
    errs = []
    for seed in range(N):
        p = f'checkpoints/iteration0_controls/inverse_{ic}_tier1_multi_fig4_ic-{ic}_seed{seed}.pkl'
        with open(p, 'rb') as f:
            c = pickle.load(f)
        errs.append(float(c['errors'][0]))
    return errs

gauss = load_control('gaussian')
sine = load_control('sine')
best_ic = 'gaussian' if np.median(gauss) < np.median(sine) else 'sine'
best = gauss if best_ic == 'gaussian' else sine

df_table_s2_multi = pd.DataFrame([{
    "agent": "Multi",
    "Opt. Iter. 0": round(float(np.median(opt_iter0)), 3),
    "Unopt. Rich": round(float(np.median(best)), 3),
    "Opt. Final": round(float(np.median(opt_final)), 4),
    "Gain": f"{np.median(best) / np.median(opt_final):.1f}x",
    "best_ic_used": best_ic,
    "gaussian_median": round(float(np.median(gauss)), 3),
    "sine_median": round(float(np.median(sine)), 3),
}])
df_table_s2_multi

,agent,Opt. Iter. 0,Unopt. Rich,Opt. Final,Gain,best_ic_used,gaussian_median,sine_median
0,Multi,3.799,0.648,0.0571,11.3x,sine,1.385,0.648